### PR TITLE
Add download links to README.md

### PR DESCRIPTION
**Pull request by darylf**
# Summary

Some less technical people might find this repository and be confused as to how to access the application. I propose we add links to the App stores in order to help these users find their intended action.

# Test instructions

n/a

# Help requested

Please review my translation of the word "Download". I'm not fluent in french.

# Unresolved questions / Out of scope

n/a

# Reviewer checklist

This is a suggested checklist of questions reviewers might ask during their review:

- [ ] Does this meet a user need?
- [x] Is it accessible?
- [x] Is it translated between both offical languages?
- [x] Is the code maintainable?
- [ ] Have you tested it?
- [ ] Are there automated tests?
- [ ] Does this cause automated test coverage to drop?
- [ ] Does this break existing functionality?
- [ ] Should this be split into smaller PRs to decrease change risk?
- [ ] Does this change the privacy policy?
- [ ] Does this introduce any security concerns?
- [ ] Does this significantly alter performance?
- [ ] What is the risk level of using added dependencies?
- [ ] Should any documentation be updated as a result of this? (i.e. README setup, etc.)

### CODE REVIEW

**Comment by pronoiac** [comment]
Working from [this page,](https://www.canada.ca/fr/sante-publique/services/maladies/maladie-coronavirus-covid-19/alerte-covid.html) there are French versions of the app / app stores. I'd suggest: 
> Télécharger: [Google Play](https://play.google.com/store/apps/details?id=ca.gc.hcsc.canada.stopcovid&hl=fr) | [l'App Store](https://apps.apple.com/ca/app/id1520284227?l=fr) 

The rest of the page uses markdown instead of html. I wrote the above as: 
```
Télécharger: [Google Play](https://play.google.com/store/apps/details?id=ca.gc.hcsc.canada.stopcovid&hl=fr) | [l'App Store](https://apps.apple.com/ca/app/id1520284227?l=fr) 
```

Referencing the page I linked: 
* I matched the store names
* 👍 on "Télécharger"

**Comment by pronoiac** [comment]
Alternate idea: add the buttons for downloading, near the top of the page.

**Comment by darylf** [comment]
Thanks for confirming my translation, and great find on the app store links! I tried searching but felt like the domains I found were France.

The reason I put HTML was so the link would open in the specified target. I wasn't sure the team would want to use images (for accessibility).

**Comment by billmei** [comment]
I think we should use this link instead, it's the centralized official download page for both iPhones and Android and will automatically update if they add more/different app stores or start supporting more devices:

https://www.canada.ca/en/public-health/services/diseases/coronavirus-disease-covid-19/covid-alert.html

**Comment by timarney** [comment]
Closing this.
We merged 
https://github.com/cds-snc/covid-alert-app/pull/982

@billmei I brought your idea back to the team as well so we may iterate on this further.

**Pull request closed without merging**
