### PR TITLE
QR code scanner view - ratio + text cut-off

### PR DESCRIPTION
**Pull request by timarney**
Fixes text issue and Camera ratio issues

- Consistency across devices 
- More inline with the Figma design

=======================================

Pixel 2 text was getting cut off and Camera view letter boxes was not ideal (black bars shown in green)

### CODE REVIEW

**Comment by timarney** [comment]
@amazingphilippe I'll do some more work on the camera ratio in a separate PR - will leave keep this PR as the text fix.

**Comment by amazingphilippe** [comment]
My latest changes should make the experience more robust across phones by just using a relative/absolute position trick. the magic numbers don't have any cropping effect on iOS, but are optimized for 4:3 cameras. The side effect for phones that have 16:9 cameras is the apparition of gray bars, which we choose to display to communicate our intentions. 

Moto G8 (4:3 camera)
Screenshot_20210603-093239
Screenshot_20210603-093253


Pixel 2 (16:9 camera)
Screenshot_20210603-093239#1
Screenshot_20210603-093453

**Comment by timarney** [comment]
iPhone SE 

unnamed

@amazingphilippe 🎈

**Review by omartehsin1 — APPROVED** [review]

**Comment by timarney** [comment]
Moto G

**Comment by timarney** [comment]
Samsung A10s

**Pull request merged**
