### PR TITLE
Fix SafeAreaView

### PR DESCRIPTION
**Pull request by henrytao-me**
# Summary

This PR removes usage of `react-native-safe-area-context` as it causes crashes on Android on prod. New `SafeAreaView` component should be used as a replacement for handling notches on both Android and iOS.

# Test instructions

Go through onboarding and all screens in the app on both Android / iOS with and without notches. 

# Help requested

> Things that you (the submitter) want reviewers to pay very close attention to when they review this.

# Unresolved questions / Out of scope

> Are there any related issues or tangent features you consider out of scope for this issue that could be addressed in the future?

# Reviewer checklist

This is a suggested checklist of questions reviewers might ask during their review:

- [x] Does this meet a user need?
- [x] Is it accessible?
- [x] Is it translated between both offical languages?
- [x] Is the code maintainable?
- [x] Have you tested it?
- [ ] Are there automated tests?
- [ ] Does this cause automated test coverage to drop?
- [ ] Does this break existing functionality?
- [ ] Should this be split into smaller PRs to decrease change risk?
- [ ] Does this change the privacy policy?
- [ ] Does this introduce any security concerns?
- [ ] Does this significantly alter performance?
- [ ] What is the risk level of using added dependencies?
- [ ] Should any documentation be updated as a result of this? (i.e. README setup, etc.)

### CODE REVIEW

**Comment by henrytao-me** [comment]
Please take over and remove `react-native-safe-area-context` in package.json if this PR is good to merge.

**Comment by nickmly** [comment]
Looks good on Android. Tested on Pixel 3XL (notch) and Nexus 4 (no notch) emulators for Android.

On iOS however I am seeing this for both iPhone 8 and 11 emulators:
Simulator Screen Shot - iPhone 8 - 2020-08-04 at 12 56 46

**Comment by henrytao-me** [comment]
Thanks @nickmly I haven't tested on iOS because my simulator doesn't run for unknown reason.

**Comment by smcmurtry** [comment]
@henrytao-me did you try this? https://github.com/cds-snc/covid-alert-app#ios-local-development

**Comment by henrytao-me** [comment]
@smcmurtry Ah ha. Thanks for the link.

**Comment by henrytao-me** [comment]
@nickmly It's fixed.

**Comment by nickmly** [comment]
Re-tested on iPhone 8 and 11 simulators, LGTM.

**Comment by timarney** [comment]
@nickmly @henrytao-me 

Just checking on Android - real device

1) When if I have the drawer menu open and go to landscape mode I can't seem to scroll the drawer menu.
2) When I go back to portrait mode and scroll the drawer menu it becomes detached.

**Comment by nickmly** [comment]
@timarney I can confirm it also happens to me with an Android emulator. It doesn't seem to happen on iOS

**Comment by janicduplessis** [comment]
@henrytao-me Do you have a stack trace for the crashes? I can try to fix it. The lib is also used internally by react-navigation so this might not completely fix the issue.

**Comment by timarney** [comment]
Hi @janicduplessis  

Here's what we're seeing in the ANR report from Google Play.

```
- waiting on <0x0274eaf1> (a java.util.concurrent.atomic.AtomicBoolean)
  at java.lang.Object.wait (Object.java:422)
  at com.th3rdwave.safeareacontext.SafeAreaView.waitForReactLayout (SafeAreaView.java:83)
- locked <0x0274eaf1> (a java.util.concurrent.atomic.AtomicBoolean)
  at com.th3rdwave.safeareacontext.SafeAreaView.updateInsets (SafeAreaView.java:54)
  at com.th3rdwave.safeareacontext.SafeAreaView.maybeUpdateInsets (SafeAreaView.java:113)
  at com.th3rdwave.safeareacontext.SafeAreaView.onAttachedToWindow (SafeAreaView.java:137)
```

I believe @smcmurtry say this doing a local build last week.


Full ANR
```

"main" prio=5 tid=1 TimedWaiting
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x7385bf28 self=0x5d8e2c3a00
  | sysTid=30277 nice=-10 cgrp=default sched=0/0 handle=0x5e12f0a9a8
  | state=S schedstat=( 0 0 0 ) utm=119 stm=28 core=4 HZ=100
  | stack=0x6cc3e17000-0x6cc3e19000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait (Native method)
- waiting on <0x0274eaf1> (a java.util.concurrent.atomic.AtomicBoolean)
  at java.lang.Object.wait (Object.java:422)
  at com.th3rdwave.safeareacontext.SafeAreaView.waitForReactLayout (SafeAreaView.java:83)
- locked <0x0274eaf1> (a java.util.concurrent.atomic.AtomicBoolean)
  at com.th3rdwave.safeareacontext.SafeAreaView.updateInsets (SafeAreaView.java:54)
  at com.th3rdwave.safeareacontext.SafeAreaView.maybeUpdateInsets (SafeAreaView.java:113)
  at com.th3rdwave.safeareacontext.SafeAreaView.onAttachedToWindow (SafeAreaView.java:137)
  at android.view.View.dispatchAttachedToWindow (View.java:17534)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3520)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3527)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3527)
  at android.view.ViewGroup.addViewInner (ViewGroup.java:5178)
  at android.view.ViewGroup.addView (ViewGroup.java:4969)
  at com.facebook.react.views.view.ReactViewGroup.addView (ReactViewGroup.java:465)
  at android.view.ViewGroup.addView (ViewGroup.java:4909)
  at com.facebook.react.views.view.ReactClippingViewManager.addView (ReactClippingViewManager.java:38)
  at com.facebook.react.views.view.ReactClippingViewManager.addView (ReactClippingViewManager.java:19)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren (NativeViewHierarchyManager.java:517)
- locked <0x02c3a6d6> (a com.facebook.react.uimanager.NativeViewHierarchyManager)
  at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute (UIViewOperationQueue.java:206)
  at com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:792)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:903)
  at com.facebook.react.uimanager.UIViewOperationQueue.access$2400 (UIViewOperationQueue.java:43)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:963)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
- locked <0x09a76d57> (a java.lang.Object)
  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1047)
  at android.view.Choreographer.doCallbacks (Choreographer.java:849)
  at android.view.Choreographer.doFrame (Choreographer.java:765)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1032)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6558)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:469)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:826)
```

**Comment by janicduplessis** [comment]
I see, the issue is caused by code in SafeAreaView that blocks the main thread to avoid flickers while react updates the layout with the safe area insets. The wait times out after 5s, but this is also the time it takes for android to trigger the ANR popup. I also found a bug that could cause the wait to last longer than 5s.

To avoid this I reduced the timeout significantly to 500ms and fixed the bug. This might cause some flicker to be visible on low end android device where the view will be drawn first without insets, then after with insets, however I don't think this is a major issue.

Published the fix in 3.1.5, would be great if you can confirm that the issue is gone. Feel free to ping me if you ever encounter other issues with this library.

**Comment by timarney** [comment]
Thanks @janicduplessis I'll add a PR will the package bump on our side.

**Comment by timarney** [comment]
Closing in favour of https://github.com/cds-snc/covid-alert-app/pull/1066

**Pull request closed without merging**
