### PR TITLE
Remove unused styles and colours from default.ts

### PR DESCRIPTION
**Pull request by smcmurtry**
# Summary | Résumé

There are a lot of styles and colours we are no longer using in default.ts. This PR removes them.

### CODE REVIEW

**Comment by timarney** [comment]
@aklef can you test with with the visual diff script?

**Comment by aklef** [comment]
> @aklef can you test with with the visual diff script?

This will be a wonderful first test of the script! Working on it!

**Comment by aklef** [comment]
Here's one view of the output from the visual-diff script! Let me know if this is helpful in any way, or if you'd rather see the raw HTML somehow... Github doesn't allow me to attach HTML to an issue

[Visual Diff - visual-diff.ios vs test-pr1454.ios.pdf](https://github.com/cds-snc/covid-alert-app/files/6111331/Visual.Diff.-.visual-diff.ios.vs.test-pr1454.ios.pdf)

**Comment by timarney** [comment]
Looks good - need to bring this up to date with latest master.

**Review by timarney — APPROVED** [review]

**Pull request merged**
