### PR TITLE
Feature/411

### PR DESCRIPTION
**Pull request by pisajew**
This aims at solving #411 by masking view contents with white screen for task switcher.

### CODE REVIEW

**Comment by jeberhardt** [comment]
Has anyone from the UI / UX team reviewed this? As I mentioned in the ticket for #411, this will occur when system dialogue boxes appear, requesting permission, and I'm not sure it's a great idea to remove the app UI when asking for permission.

**Comment by henrytao-me** [comment]
More screenshots for reviewing 

|  image | image |
|---|---|

**Comment by smcmurtry** [comment]
> As I mentioned in the ticket for #411, this will occur when system dialogue boxes appear, requesting permission...
I am not observing the blank screen behind system dialogue boxes on ios or android for this PR.

**Comment by jeberhardt** [comment]
> I am not observing the blank screen behind system dialogue boxes on ios or android for this PR.

If we wanted the screen to go blank, at least for iOS, when the system dialogue boxes appear, `sceneWillResignActive:
` and `sceneDidBecomeActive:` will have to be implemented, and perform the same function as `sceneDidEnterBackground:` and `sceneWillEnterForeground:` are currently doing.

**Comment by timarney** [comment]
Holding this until at the moment for other priority items.

**Comment by timarney** [comment]
Closes this pending further discussion we'll re-open as needed.

**Pull request closed without merging**
