### PR TITLE
use in-ecosystem URL for reachability, instead of leaking info to Google

### PR DESCRIPTION
**Pull request by scoates**
# Summary

The app leaks IP addresses to Google. This fixes it. Explanation in [issue](https://github.com/cds-snc/covid-alert-app/issues/1003).

# Test instructions

You'll need [this PR](https://github.com/cds-snc/covid-alert-server/pull/241) deployed before this can really be tested. Once ready, analyze traffic to be sure that no data is flowing to Google, and instead is staying local on `canada.ca`

# Reviewer checklist

This is a suggested checklist of questions reviewers might ask during their review:

- [ ] Does this meet a user need?
- [ ] Is it accessible?
- [ ] Is it translated between both offical languages?
- [ ] Is the code maintainable?
- [ ] Have you tested it?
- [ ] Are there automated tests?
- [ ] Does this cause automated test coverage to drop?
- [ ] Does this break existing functionality?
- [ ] Should this be split into smaller PRs to decrease change risk?
- [ ] Does this change the privacy policy?
- [ ] Does this introduce any security concerns?
- [ ] Does this significantly alter performance?
- [ ] What is the risk level of using added dependencies?
- [ ] Should any documentation be updated as a result of this? (i.e. README setup, etc.)

### CODE REVIEW

**Comment by timarney** [comment]
@scoates noting we have eyes on this and will review as soon as we can.

cc: @obrien-j @lchski

**Comment by scoates** [comment]
@timarney thanks; I appreciate it. Just to be *super* clear, the real issue is in #1003 ; this is the PR for that. Didn't want the server side change to slip through the cracks, just in case.

**Comment by timarney** [comment]
```
    @react-native-community/netinfo: NativeModule.RNCNetInfo is null. To fix this issue try these steps:
```

Not sure if this is the issue but will note this for failing CI to look into https://github.com/react-native-community/react-native-netinfo/issues/63#issuecomment-650824396 

@nickmly perhaps you can take a look tomorrow

**Comment by nickmly** [comment]
@timarney Seems the CI issue is due to this: https://github.com/react-native-community/react-native-netinfo#errors-while-running-jest-tests

Adding in the `jest.setup.js` file and mocking the module works for me locally.

**Comment by nickmly** [comment]
I will work on these changes now.

**Comment by scoates** [comment]
Closing in favour of #1008

**Pull request closed without merging**
