### PR TITLE
Issue 800 added padding in bottom

### PR DESCRIPTION
**Pull request by mtropper**
Issue #800 
* Added padding in bottom so it's less covered by the overlay.

### CODE REVIEW

**Comment by henrytao-me** [comment]
Good catch @smcmurtry 👍

**Comment by mtropper** [comment]
@smcmurtry in IOS normally the bullet and the text are read together but looks like android doesn't follow that rule. I feel its redundant to swipe twice to get the content of each bullet. But I guess its a personal preference. I'll revert it back. 
Screenshot 2020-07-23 at 1 30 13 PM

**Comment by mtropper** [comment]
@smcmurtry when I was looking at your comment earlier, I could only see the still image. Now I can see the animation. That does seems weird. Locally it just reads the bullet and the text together. I will remove that

**Comment by mtropper** [comment]
> I don't think we actually want the `accessible accessibilityRole="button"` props on the `Box` component. The `ButtonSingleLine` component already has the `accessibilityRole= "button"` prop ([ref](https://github.com/cds-snc/covid-shield-mobile/blob/master/src/components/ButtonSingleLine.tsx#L117)). And touchable elements like the button have the `accessible` prop set to true by default.
> 
> Sorry I didn't catch this on my 1st review!

@smcmurtry the tag was added to the box so the focus would go to both the button and the padding below the button so talk back and Voiceover to scroll the button higher up so its not covered by the overly. Otherwise it will not scroll enough for the button to not be under the overlay.

**Comment by timarney** [comment]
> Can the bottom of these pages have some additional padding added to help with the issue?

My original comment was to see if we could add to the bottom of the **pages.**  

I haven't checked out this PR but looks like padding was added to the button .

@amazingphilippe should comment before anything gets merged here.

**Comment by mtropper** [comment]
> > Can the bottom of these pages have some additional padding added to help with the issue?
> 
> My original comment was to see if we could add to the bottom of the **pages.**
> 
> I haven't checked out this PR but looks like padding was added to the button .
> 
> @amazingphilippe should comment before anything gets merged here.

@timarney  The problem isn't with there not being enough padding in the bottom. The problem is that the screen reader doesn't see the overlay at the bottom. So as soon as the button is at the bottom of the page it stops scrolling which puts the button behind the overlay.

**Comment by amazingphilippe** [comment]
I don't know if button padding solves the issue in the most graceful way. Is there a way to make voiceover aware of the bottom fade? My worry is about the voiceover outline being larger than what it needs. Furthermore, voice over reads out the item, so I wouldn't worry about readability. @JuliannaR would there be a scenario where a user uses voice over, without listening to the voice? just for navigation?

**Pull request closed without merging**
