### PR TITLE
Update EN to 1.6 on Android

### PR DESCRIPTION
**Pull request by henrytao-me**
This PR updates EN to use version 1.5 on Android, including:

- Update EN version. 
- Handle `ACTION_EXPOSURE_NOT_FOUND` which is a callback when no exposure detected. Ref https://github.com/google/exposure-notifications-android/blob/master/app/src/main/java/com/google/android/apps/exposurenotification/nearby/ExposureNotificationBroadcastReceiver.java#L33
- Changes logic of `detectExposure` on Android to match iOS because from EN 1.5, the framework will return summary regardless matchedKeyCount has value or not.
- Changes logic of `shouldStartHeadlessJsTask` checking for existence of `currentReactContext` instead of MainActivity because: 
  + MainActivity check is only for app when it is minimized. 
  + When app is terminated and broadcast receiver calls onReceive or regular periodic task runs, a React Native JS instance is run in the background without MainActivity. 

Resolves https://github.com/cds-snc/covid-alert-app/issues/453

## How to test?

We need to verify 4 scenarios:
- App in foreground
- App is minimized
- App is terminated after pass onboarding but before broadcast receiver sends data back
- App is terminated and background job runs

### Verify EN framework returns summary with exposed state
- Build the app on device that already has exposed state from previous build (master).
- Go through onboarding flow. 
- Verify that the device changes to exposed state. It may take about 40s to a minute for Android broadcast receiver to send summary back. So, please wait until `finalize` is being called. 
- The log looks like this 

JS log
```
[Tue Jul 28 2020 13:58:39.715]  LOG      registerAndroidHeadlessPeriodicTask {}
[Tue Jul 28 2020 13:58:39.715]  LOG      Running "CovidShield" with {"rootTag":1}
[Tue Jul 28 2020 13:58:40.280]  LOG      App.appInit() {}
[Tue Jul 28 2020 13:58:42.658]  LOG      registerPeriodicTask {"result": true}
[Tue Jul 28 2020 13:58:48.937]  LOG      getExposureConfiguration {"exposureConfigurationUrl": "http://192.168.43.51:8001/exposure-configuration/CA.json"}
[Tue Jul 28 2020 13:58:49.470]  LOG      Using downloaded exposureConfiguration. {}
[Tue Jul 28 2020 13:58:49.113]  LOG      Saving exposure configuration to secure storage. {}
[Tue Jul 28 2020 13:58:49.118]  LOG      retrieveDiagnosisKeys {"period": 0, "url": "http://192.168.43.51:8001/retrieve/302/00000/9d7dcbd0446b03f127019fb40df47b59d760dbf4817d01f134c438d478ac94be"}
[Tue Jul 28 2020 13:58:49.153]  LOG      performExposureStatusUpdate {"exposureConfiguration": {"attenuationLevelValues": [0, 0, 2, 2, 2, 2, 2, 2], "attenuationWeight": 50, "daysSinceLastExposureLevelValues": [0, 1, 1, 1, 1, 1, 1, 1], "daysSinceLastExposureWeight": 50, "durationLevelValues": [0, 0, 0, 0, 5, 5, 5, 5], "durationWeight": 50, "minimumRiskScore": 1, "transmissionRiskLevelValues": [1, 1, 1, 1, 1, 1, 1, 1], "transmissionRiskWeight": 50}, "keysFileUrls": ["/data/user/0/ca.gc.hcsc.canada.stopcovid/app_ab861db1-4c6b-4c8c-b874-3ffba727234f/keys.zip"], "lastCheckedPeriod": 18471}
[Tue Jul 28 2020 13:59:33.787]  LOG      summary {"summary": {"_summaryIdx": "f58a5c90-a92d-45aa-a0ab-1f00cb406727-1595959132495", "daysSinceLastExposure": 2, "lastExposureTimestamp": 1595786376975, "matchedKeyCount": 21, "maximumRiskScore": 10}}
[Tue Jul 28 2020 13:59:34.449]  LOG      finalize {"currentExposureStatus": {"lastChecked": {"period": 18471, "timestamp": 1595959176991}, "summary": {"_summaryIdx": "f58a5c90-a92d-45aa-a0ab-1f00cb406727-1595959132495", "daysSinceLastExposure": 2, "lastExposureTimestamp": 1595786376975, "matchedKeyCount": 21, "maximumRiskScore": 10}, "type": "exposed"}, "previousExposureStatus": {"type": "monitoring"}}
```

Android logcat (note the `onReceive {action=com.google.android.gms.exposurenotification.ACTION_EXPOSURE_STATE_UPDATED}`)

```
2020-07-28 13:59:36.754 22220-22220/? D/CovidShield ExposureNotificationBroadcastReceiver: onReceive {action=com.google.android.gms.exposurenotification.ACTION_EXPOSURE_STATE_UPDATED}
2020-07-28 13:59:36.785 22220-22220/? D/CovidShield ExposureNotificationBroadcastReceiver: startStateUpdateWorker {token=f58a5c90-a92d-45aa-a0ab-1f00cb406727-1595959132495}
2020-07-28 13:59:36.904 22220-22348/? D/CovidShield StateUpdatedWorker: StateUpdatedWorker {token=f58a5c90-a92d-45aa-a0ab-1f00cb406727-1595959132495}
2020-07-28 13:59:36.914 22220-22266/? I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=a19fcb42-ddbd-490a-8fb4-19f12c0dbc63, tags={ app.covidshield.receiver.worker.StateUpdatedWorker } ]
2020-07-28 13:59:36.967 22220-22349/? D/CovidShield StandaloneCoroutine: detectExposure {token=f58a5c90-a92d-45aa-a0ab-1f00cb406727-1595959132495, summary=Summary(daysSinceLastExposure=2, matchedKeyCount=21, maximumRiskScore=10)}
```

### Verify EN framework returns summary even there is no matched key count
- Build the app on device that doesn't have exposed state from previous build (master).
- Go through onboarding flow. 
- Verify that the device keeps at `You're all set`.
- The log looks like this 

JS log

```
Tue Jul 28 2020 14:14:28.730]  LOG      registerAndroidHeadlessPeriodicTask {}
[Tue Jul 28 2020 14:14:28.731]  LOG      Running "CovidShield" with {"rootTag":21}
[Tue Jul 28 2020 14:14:28.963]  LOG      App.appInit() {}
[Tue Jul 28 2020 14:14:29.976]  LOG      registerPeriodicTask {"result": true}
[Tue Jul 28 2020 14:14:47.179]  LOG      getExposureConfiguration {"exposureConfigurationUrl": "http://192.168.43.51:8001/exposure-configuration/CA.json"}
[Tue Jul 28 2020 14:14:47.353]  LOG      Using downloaded exposureConfiguration. {}
[Tue Jul 28 2020 14:14:47.474]  LOG      Saving exposure configuration to secure storage. {}
[Tue Jul 28 2020 14:14:47.494]  LOG      retrieveDiagnosisKeys {"period": 0, "url": "http://192.168.43.51:8001/retrieve/302/00000/e35c0bfbe00bbe48c5260932c8a9303fb11aa8f063f09b1dc17c1fe17f622d33"}
[Tue Jul 28 2020 14:14:47.615]  LOG      performExposureStatusUpdate {"exposureConfiguration": {"attenuationLevelValues": [0, 0, 2, 2, 2, 2, 2, 2], "attenuationWeight": 50, "daysSinceLastExposureLevelValues": [0, 1, 1, 1, 1, 1, 1, 1], "daysSinceLastExposureWeight": 50, "durationLevelValues": [0, 0, 0, 0, 5, 5, 5, 5], "durationWeight": 50, "minimumRiskScore": 1, "transmissionRiskLevelValues": [1, 1, 1, 1, 1, 1, 1, 1], "transmissionRiskWeight": 50}, "keysFileUrls": ["/data/user/0/ca.gc.hcsc.canada.stopcovid/app_aca32f68-c29f-4dd3-abd9-62bc1f009d72/keys.zip"], "lastCheckedPeriod": 18471}
[Tue Jul 28 2020 14:14:48.541]  LOG      summary {"summary": {"_summaryIdx": "60f01acb-1f89-4942-aa4d-27a66241b7c1-1595960090901", "daysSinceLastExposure": 2147483647, "lastExposureTimestamp": 0, "matchedKeyCount": 0, "maximumRiskScore": 0}}
[Tue Jul 28 2020 14:14:48.668]  LOG      finalize {"currentExposureStatus": {"lastChecked": {"period": 18471, "timestamp": 1595960091811}, "type": "monitoring"}, "previousExposureStatus": {"type": "monitoring"}}
```

Android logcat (note the `onReceive {action=com.google.android.gms.exposurenotification.ACTION_EXPOSURE_NOT_FOUND}`)

```
2020-07-28 14:14:55.625 30681-30681/? D/CovidShield ExposureNotificationBroadcastReceiver: onReceive {action=com.google.android.gms.exposurenotification.ACTION_EXPOSURE_NOT_FOUND}
2020-07-28 14:14:55.634 30681-30681/? D/CovidShield ExposureNotificationBroadcastReceiver: startStateUpdateWorker {token=74adcbc4-f4ea-45d0-ba5e-e2ae1c8ebda7-1595960094934}
2020-07-28 14:14:55.784 30681-30789/? D/CovidShield StateUpdatedWorker: StateUpdatedWorker {token=74adcbc4-f4ea-45d0-ba5e-e2ae1c8ebda7-1595960094934}
2020-07-28 14:14:55.792 30681-30727/? I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=3c065640-702a-451e-9db5-00a24316b675, tags={ app.covidshield.receiver.worker.StateUpdatedWorker } ]
2020-07-28 14:14:55.884 30681-30788/? D/CovidShield StandaloneCoroutine: detectExposure {token=74adcbc4-f4ea-45d0-ba5e-e2ae1c8ebda7-1595960094934, summary=Summary(daysSinceLastExposure=2147483647, matchedKeyCount=0, maximumRiskScore=0)}
```

### Verify `getPendingExposureSummary` works:
- Build the app on device that already has exposed state from previous build (master).
- Go through onboarding flow and quickly terminate the app. 
- Wait for exposed notification to show up (likely a min). 
- Keep observe JS log for the next 90 mins (or modify `EXACT_JOB_INTERNVAL_IN_MINUTES` to 15 mins) and verify if the `performExposureStatusUpdate` should be called again from regular background job and there is no infinite loop.
- The log looks like this 

JS log

```
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Wed Jul 29 2020 09:13:50.638]  LOG      registerAndroidHeadlessPeriodicTask {}
[Wed Jul 29 2020 09:13:50.639]  LOG      Running "CovidShield" with {"rootTag":21}
[Wed Jul 29 2020 09:13:50.753]  LOG      App.appInit() {}
[Wed Jul 29 2020 09:13:51.731]  LOG      registerPeriodicTask {"result": true}
[Wed Jul 29 2020 09:14:04.300]  LOG      getExposureConfiguration {"exposureConfigurationUrl": "http://192.168.0.24:8001/exposure-configuration/CA.json"}
[Wed Jul 29 2020 09:14:04.134]  LOG      Using downloaded exposureConfiguration. {}
[Wed Jul 29 2020 09:14:04.216]  LOG      Saving exposure configuration to secure storage. {}
[Wed Jul 29 2020 09:14:04.222]  LOG      retrieveDiagnosisKeys {"period": 0, "url": "http://192.168.0.24:8001/retrieve/302/00000/f6bbb74c36c6f1cacfc0fa3930b29a954486b73b3c64284fa600916a3108d6f6"}
[Wed Jul 29 2020 09:14:04.259]  LOG      performExposureStatusUpdate {"exposureConfiguration": {"attenuationLevelValues": [0, 0, 2, 2, 2, 2, 2, 2], "attenuationWeight": 50, "daysSinceLastExposureLevelValues": [0, 1, 1, 1, 1, 1, 1, 1], "daysSinceLastExposureWeight": 50, "durationLevelValues": [0, 0, 0, 0, 5, 5, 5, 5], "durationWeight": 50, "minimumRiskScore": 1, "transmissionRiskLevelValues": [1, 1, 1, 1, 1, 1, 1, 1], "transmissionRiskWeight": 50}, "keysFileUrls": ["/data/user/0/ca.gc.hcsc.canada.stopcovid/app_5075c8fd-255a-4191-ab2f-aafbc4cedceb/keys.zip"], "lastCheckedPeriod": 18472}
[Wed Jul 29 2020 09:14:56.355]  BUNDLE  ./index.js 

[Wed Jul 29 2020 09:15:10.587]  WARN     Require cycle: node_modules/protobufjs/src/util/minimal.js -> node_modules/protobufjs/src/util/longbits.js -> node_modules/protobufjs/src/util/minimal.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Wed Jul 29 2020 09:15:10.588]  WARN     Require cycle: src/components/index.ts -> src/components/BulletPointX.tsx -> src/components/index.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Wed Jul 29 2020 09:15:10.588]  WARN     Require cycle: src/components/index.ts -> src/components/BulletPointCheck.tsx -> src/components/index.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Wed Jul 29 2020 09:15:10.588]  WARN     Require cycle: src/components/index.ts -> src/components/BulletPointPurple.tsx -> src/components/index.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Wed Jul 29 2020 09:15:10.589]  WARN     Require cycle: src/components/index.ts -> src/components/TextMultiline.tsx -> src/components/index.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Wed Jul 29 2020 09:15:10.589]  WARN     Require cycle: src/components/index.ts -> src/components/LastCheckedDisplay.tsx -> src/components/index.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Wed Jul 29 2020 09:15:10.590]  WARN     Require cycle: src/screens/onboarding/OnboardingContent.tsx -> src/screens/onboarding/views/Start.tsx -> src/screens/onboarding/views/ItemView.tsx -> src/screens/onboarding/OnboardingContent.tsx

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Wed Jul 29 2020 09:15:10.590]  LOG      registerAndroidHeadlessPeriodicTask {}
[Wed Jul 29 2020 09:15:10.590]  LOG      runAndroidHeadlessPeriodicTask {"taskId": "EXPOSURE_NOTIFICATION_BROADCAST_RECEIVER"}
[Wed Jul 29 2020 09:15:10.820]  LOG      updateExposureStatusInBackground {"exposureStatus": {"type": "monitoring"}}
[Wed Jul 29 2020 09:15:11.712]  LOG      updatedExposureStatusInBackground {"exposureStatus": {"lastChecked": {"period": 18472, "timestamp": 1596028515788}, "notificationSent": true, "summary": {"_summaryIdx": "c9564e0a-7535-458c-a52c-a734e3d11bf1-1596028448480", "daysSinceLastExposure": 3, "lastExposureTimestamp": 1595769315788, "matchedKeyCount": 19, "maximumRiskScore": 10}, "type": "exposed"}}
[Wed Jul 29 2020 09:29:42.791]  BUNDLE  ./index.js 

[Wed Jul 29 2020 09:29:55.238]  WARN     Require cycle: node_modules/protobufjs/src/util/minimal.js -> node_modules/protobufjs/src/util/longbits.js -> node_modules/protobufjs/src/util/minimal.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Wed Jul 29 2020 09:29:55.239]  WARN     Require cycle: src/components/index.ts -> src/components/BulletPointX.tsx -> src/components/index.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Wed Jul 29 2020 09:29:55.239]  WARN     Require cycle: src/components/index.ts -> src/components/BulletPointCheck.tsx -> src/components/index.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Wed Jul 29 2020 09:29:55.239]  WARN     Require cycle: src/components/index.ts -> src/components/BulletPointPurple.tsx -> src/components/index.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Wed Jul 29 2020 09:29:55.241]  WARN     Require cycle: src/components/index.ts -> src/components/TextMultiline.tsx -> src/components/index.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Wed Jul 29 2020 09:29:55.241]  WARN     Require cycle: src/components/index.ts -> src/components/LastCheckedDisplay.tsx -> src/components/index.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Wed Jul 29 2020 09:29:55.241]  WARN     Require cycle: src/screens/onboarding/OnboardingContent.tsx -> src/screens/onboarding/views/Start.tsx -> src/screens/onboarding/views/ItemView.tsx -> src/screens/onboarding/OnboardingContent.tsx

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Wed Jul 29 2020 09:29:55.242]  LOG      registerAndroidHeadlessPeriodicTask {}
[Wed Jul 29 2020 09:29:55.242]  LOG      runAndroidHeadlessPeriodicTask {"taskId": "react-native-background-fetch"}
[Wed Jul 29 2020 09:29:55.546]  LOG      updateExposureStatusInBackground {"exposureStatus": {"lastChecked": {"period": 18472, "timestamp": 1596028515788}, "notificationSent": true, "summary": {"_summaryIdx": "c9564e0a-7535-458c-a52c-a734e3d11bf1-1596028448480", "daysSinceLastExposure": 3, "lastExposureTimestamp": 1595769315788, "matchedKeyCount": 19, "maximumRiskScore": 10}, "type": "exposed"}}
[Wed Jul 29 2020 09:29:56.520]  LOG      getExposureConfiguration {"exposureConfigurationUrl": "http://192.168.0.24:8001/exposure-configuration/CA.json"}
[Wed Jul 29 2020 09:29:56.309]  LOG      Using downloaded exposureConfiguration. {}
[Wed Jul 29 2020 09:29:56.425]  LOG      Saving exposure configuration to secure storage. {}
[Wed Jul 29 2020 09:29:56.438]  LOG      retrieveDiagnosisKeys {"period": 18472, "url": "http://192.168.0.24:8001/retrieve/302/18472/dd914690165c7afeec2bb8071a23bed5c48e44e8ba887603f3d4758816b7dddb"}
[Wed Jul 29 2020 09:29:56.497]  LOG      performExposureStatusUpdate {"exposureConfiguration": {"attenuationLevelValues": [0, 0, 2, 2, 2, 2, 2, 2], "attenuationWeight": 50, "daysSinceLastExposureLevelValues": [0, 1, 1, 1, 1, 1, 1, 1], "daysSinceLastExposureWeight": 50, "durationLevelValues": [0, 0, 0, 0, 5, 5, 5, 5], "durationWeight": 50, "minimumRiskScore": 1, "transmissionRiskLevelValues": [1, 1, 1, 1, 1, 1, 1, 1], "transmissionRiskWeight": 50}, "keysFileUrls": ["/data/user/0/ca.gc.hcsc.canada.stopcovid/app_48805f03-436d-4d14-9a08-0549c6b0a1dc/keys.zip"], "lastCheckedPeriod": 18472}
[Wed Jul 29 2020 09:29:57.670]  LOG      summary {"summary": {"_summaryIdx": "ebb27adc-1a0a-4d2e-8bf9-a7c8476315d5-1596029400821", "daysSinceLastExposure": 2147483647, "lastExposureTimestamp": 0, "matchedKeyCount": 0, "maximumRiskScore": 0}}
[Wed Jul 29 2020 09:29:57.677]  LOG      finalize {"currentExposureStatus": {"lastChecked": {"period": 18472, "timestamp": 1596029401784}, "notificationSent": true, "summary": {"_summaryIdx": "c9564e0a-7535-458c-a52c-a734e3d11bf1-1596028448480", "daysSinceLastExposure": 3, "lastExposureTimestamp": 1595769315788, "matchedKeyCount": 19, "maximumRiskScore": 10}, "type": "exposed"}, "previousExposureStatus": {"lastChecked": {"period": 18472, "timestamp": 1596028515788}, "notificationSent": true, "summary": {"_summaryIdx": "c9564e0a-7535-458c-a52c-a734e3d11bf1-1596028448480", "daysSinceLastExposure": 3, "lastExposureTimestamp": 1595769315788, "matchedKeyCount": 19, "maximumRiskScore": 10}, "type": "exposed"}}
[Wed Jul 29 2020 09:29:57.677]  LOG      updatedExposureStatusInBackground {"exposureStatus": {"lastChecked": {"period": 18472, "timestamp": 1596029401784}, "notificationSent": true, "summary": {"_summaryIdx": "c9564e0a-7535-458c-a52c-a734e3d11bf1-1596028448480", "daysSinceLastExposure": 3, "lastExposureTimestamp": 1595769315788, "matchedKeyCount": 19, "maximumRiskScore": 10}, "type": "exposed"}}
```

Android logcat

```
2020-07-29 09:14:59.944 9260-9260/? D/CovidShield ExposureNotificationBroadcastReceiver: onReceive {action=com.google.android.gms.exposurenotification.ACTION_EXPOSURE_STATE_UPDATED}
2020-07-29 09:14:59.961 9260-9260/? D/CovidShield ExposureNotificationBroadcastReceiver: startHeadlessJsTaskWorker {token=c9564e0a-7535-458c-a52c-a734e3d11bf1-1596028448480}
2020-07-29 09:15:00.400 9260-9365/? D/CovidShield HeadlessJsTaskWorker: HeadlessJsTaskWorker {shouldStartHeadlessJsTask=true}
2020-07-29 09:15:04.969 9260-9260/? D/CovidShield CustomHeadlessTask: onHeadlessJsTaskStart {}
2020-07-29 09:15:15.602 9260-9365/? D/CovidShield StandaloneCoroutine: getPendingExposureSummary {summary=Summary(daysSinceLastExposure=3, matchedKeyCount=19, maximumRiskScore=10), token=c9564e0a-7535-458c-a52c-a734e3d11bf1-1596028448480}
2020-07-29 09:15:15.934 9260-9260/? D/CovidShield CustomHeadlessTask: onHeadlessJsTaskFinish {}
2020-07-29 09:15:15.960 9260-9336/? I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=95f05df4-b91f-4328-8c6f-848ee5c52092, tags={ app.covidshield.receiver.worker.HeadlessJsTaskWorker } ]
2020-07-29 09:23:55.963 11428-11428/? W/System.err:     at app.covidshield.MainApplication.onCreate(MainApplication.java:78)
2020-07-29 09:23:56.201 11428-11428/? D/TSBackgroundFetch: - stop: app.covidshield.exposure-notification
2020-07-29 09:23:56.205 11428-11428/? I/TSBackgroundFetch: - cancel taskId=app.covidshield.exposure-notification, jobId=742351172
2020-07-29 09:29:45.829 12983-12983/? W/System.err:     at app.covidshield.MainApplication.onCreate(MainApplication.java:78)
2020-07-29 09:30:00.202 12983-13270/? D/CovidShield StandaloneCoroutine: getPendingExposureSummary {summary=null, token=null}
2020-07-29 09:30:00.822 12983-13270/? D/CovidShield StandaloneCoroutine: detectExposure {token=ebb27adc-1a0a-4d2e-8bf9-a7c8476315d5-1596029400821, files=[/data/user/0/ca.gc.hcsc.canada.stopcovid/app_48805f03-436d-4d14-9a08-0549c6b0a1dc/keys.zip]}
2020-07-29 09:30:01.503 12983-12983/? D/CovidShield ExposureNotificationBroadcastReceiver: onReceive {action=com.google.android.gms.exposurenotification.ACTION_EXPOSURE_NOT_FOUND}
2020-07-29 09:30:01.509 12983-12983/? D/CovidShield ExposureNotificationBroadcastReceiver: startStateUpdateWorker {token=ebb27adc-1a0a-4d2e-8bf9-a7c8476315d5-1596029400821}
2020-07-29 09:30:01.647 12983-13270/? D/CovidShield StateUpdatedWorker: StateUpdatedWorker {token=ebb27adc-1a0a-4d2e-8bf9-a7c8476315d5-1596029400821}
2020-07-29 09:30:01.660 12983-13116/? I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=e507ac25-2491-49d6-9c1e-d0f2d5d49b4b, tags={ app.covidshield.receiver.worker.StateUpdatedWorker } ]
2020-07-29 09:30:01.769 12983-13269/? D/CovidShield StandaloneCoroutine: detectExposure {token=ebb27adc-1a0a-4d2e-8bf9-a7c8476315d5-1596029400821, summary=Summary(daysSinceLastExposure=2147483647, matchedKeyCount=0, maximumRiskScore=0)}
```

### Optional: try `Clear exposure history and run check` in both scenarios above and observe the result.

### CODE REVIEW

**Comment by henrytao-me** [comment]
Tested again. There is still a bug with looping exposure checks in the background.

**Comment by henrytao-me** [comment]
Tested. LGTM

**Comment by henrytao-me** [comment]
```
- App in foreground
- App is minimized
- App is terminated after pass onboarding but before boardcast receiver sends data back
- App is terminated and background job runs
```

**Comment by timarney** [comment]
@henrytao-me if you get a chance to re-test this on your devices with all the updates from master rolled in that would be great.

Testing on our end this week.

**Comment by henrytao-me** [comment]
Sure. I will take a look sometime this week asap.

**Comment by timarney** [comment]
@jeberhardt we can either update this PR to use https://github.com/google/exposure-notifications-android/blob/master/app/libs/play-services-nearby-exposurenotification-1.6.1-eap.aar or make another PR and change it.

**Comment by jeberhardt** [comment]
> Will wait for @henrytao-me and testing on your end before we merge.

I've done my end-to-end testing, with 1.6 on 2 Android phones, and 1 phone was able to get into `diagnosed` mode, and the other phone became `exposed` after a 15 minute exposure. 

I conclude that the upgrade to 1.6 is successful.

**Comment by henrytao-me** [comment]
My environment is messed up. I cannot sync gradle properly. I will continue testing tomorrow.

**Comment by henrytao-me** [comment]
Tested with shorter rolling period (v1.6). Both uploading keys and exposed state work. 👍 

image

**Comment by timarney** [comment]
Need to fix up the conflict - after that we'll get a release date sorted out for this before merging.

**Comment by timarney** [comment]
Have a few more PRs to go in before this but we're good to merge this soon.

**Comment by emilykuret** [comment]
[Explore restructuring the menu](https://trello.com/c/wlYxBsAd/293-explore-restructuring-the-menu)

**Pull request merged**
