### PR TITLE
fixed deleteAll and fr time issue

### PR DESCRIPTION
**Pull request by omartehsin1**
# Summary | Résumé

Takes care of the incorrect "Delete All" subtitle
Also takes care of the FR time issue

### CODE REVIEW

**Comment by timarney** [comment]
@EliseKa 

Just reviewing on my end - we'll create another build but here's a preview if you can comment (approve or needs further adjustments)

image

**Comment by EliseKa** [comment]
Time format looks good!

**Comment by timarney** [comment]
@EliseKa here's the other screen.

image

**Comment by EliseKa** [comment]
@timarney this pop up about deleting a single visit was fine - it was the one about deleting all visits that had an issue

**Pull request merged**
