### PR TITLE
Feature/remove unused unimodules

### PR DESCRIPTION
**Pull request by craigzour**
# Summary | Résumé

- Removed unused unimodules

### CODE REVIEW

**Review by jeberhardt — APPROVED** [review]
I tested this by uploading a build to the Google Play store with the 2nd bundle ID, to verify that the remaining permissions allowed the camera to still function.

**Comment by timarney** [comment]
Can we remove these commented lines from the Manifest?

**Comment by craigzour** [comment]
@timarney I removed the permissions from all our AndroidManifest files https://github.com/cds-snc/covid-alert-app/pull/1570/commits/2fbb6a8f5a1f895a0a5f5fb40387eda390ffc8c1 . Is it correct?

**Comment by timarney** [comment]
Looks good.

**Pull request merged**
