### PR TITLE
Accessibility list functionality for the Privacy Policy

### PR DESCRIPTION
**Pull request by jelen-HC**
The necessary changes have been made to the privacy policy and bulletpoint list items to enable proper accessibility for the lists found within the privacy policy. 

This primarily being the conversion of the current privacy policy files over to json within the json locale files, as there is no way to support proper list accessibility functionality with the privacy policy being generate via markup. The corresponding components, such as BulletPoint.tsx, and Privacy.tsx have been updated to support this change as well.

### CODE REVIEW

**Comment by timarney** [comment]
@JuliannaR 

I've tested this - Android and iOS announces list start / end etc...

----------------------------------------------------------------

1) @JuliannaR  - I would like to get some other folks to test can you coordinate that? 
2) @lchski @katewilhelm - this PR moves all the copy to the json files - 
    a) Does that work for you
    b) we need to ensure this PR has the latest content


@emilykuret ☝️ for line of sight

**Comment by katewilhelm** [comment]
I'm curious how the headings work in JSON? Also is there a way to preview the new version?

**Comment by timarney** [comment]
@dsamojlenko can we try out the Ad-hoc (PR review builds) with this PR next week?

i would be a good chance to test with 

cc: @katewilhelm @lchski @JuliannaR

**Comment by timarney** [comment]
Closing this but adding it to our Trello backlog to be looked at again moving forward.

**Pull request closed without merging**
