### PR TITLE
Feature/android notification channel label

### PR DESCRIPTION
**Pull request by jeberhardt**
# Summary | Résumé

The notification channel in Android was displaying EN copy when the user had selected FR for the language. This is because the Channel Name had not been localized. This change localizes that string, and passes it to Android.

# Test instructions | Instructions pour tester la modification

- Launch the App in Android 8 or above.
- Select Français for the language.
- Open the Demo menu, and tap the button: "Show sample notification".
- Observe the notification appear.
- Open the system **Settings**, choose **Apps & notifications**, and then **COVID Alert**
- Tap on **Notifications**
- You should see the channel name for the app: **Alerte COVID**
 
# Help requested | Aide requise

This has not been tested on iOS to ensure no breaking changes on the iOS side.

### CODE REVIEW

**Comment by timarney** [comment]
Tested per notes above ✅ 

Seeing this for settings - is this the expected result?  2 channels was thinking I would see one localized.

**Comment by timarney** [comment]
Might work?
deleteNotificationChannel()
https://developer.android.com/reference/android/app/NotificationManager#deleteNotificationChannel(java.lang.String)

**Comment by maryrae-qa** [comment]
Tested with 1.1.8 (218) Android V9 EN/FR


Notify_EN
Notify_FR
Notify_FR
Notify_EN

Looks good. Will also complete on Android V8 EN/FR

**Comment by maryrae-qa** [comment]
Tested with build 1.1.8 (218) on Android V9 - Looks good for both EN/FR. Will test on Android V8 also.

**Comment by maryrae-qa** [comment]
Tested with build 1.1.8 (218) on Android V8 - Looks good for both EN/FR.

**Comment by timarney** [comment]
@jeberhardt are you going to update with the deleteNotificationChannel in this PR?

**Comment by timarney** [comment]
@jeberhardt just the merge conflict to fix on this one.

**Comment by jeberhardt** [comment]
> Seeing this for settings - is this the expected result i.e. 2 channels? I was thinking I would see one localized.

The old channel names are deleted in PR #1370

**Review by timarney — APPROVED** [review]

**Pull request merged**
