### PR TITLE
Update exposed screen for non covered regions

### PR DESCRIPTION
**Pull request by timarney**
**Figma**
https://www.figma.com/file/0pLawavG1fnBTXSYn4pdKZ/Exposure-notification?node-id=12675%3A0

**No region or non  active region**:

 

**Active region i.e. QC**:

### CODE REVIEW

**Comment by timarney** [comment]
Bolded the purple button text per figma

**Comment by timarney** [comment]
Noting: Reviewed on a call with @katewilhelm and @EliseKa

**Review by smcmurtry — APPROVED** [review]
Looks good and matches Figma.

**Comment by smcmurtry** [comment]
Reviewed again w/ @katewilhelm and this change is good to go.

**Pull request merged**
