### PR TITLE
Menu padding

### PR DESCRIPTION
**Pull request by timarney**
**Updated**

**Current**

### CODE REVIEW

**Comment by amazingphilippe** [comment]
Wondering if we should use a SafeAreaView to detect the bottom edge for iphone 11 and similar? 

With:
Capture d’écran, le 2021-03-26 à 10 52 47


Without: 
Capture d’écran, le 2021-03-26 à 10 54 02

**Comment by timarney** [comment]
Yes we can try that seeing quite a bit of variance across devices.

**Comment by timarney** [comment]
Updated with SafeArea

Screen Shot 2021-03-30 at 12 12 29 PM

**Comment by timarney** [comment]
Updated to handle SafeArea padding depending on aspect ratio

Screen Shot 2021-03-30 at 2 05 36 PM

Screen Shot 2021-03-30 at 2 05 55 PM

**Review by jeberhardt — APPROVED** [review]

**Comment by timarney** [comment]
Example landscape

Screen Shot 2021-03-30 at 2 09 59 PM

**Comment by aklef** [comment]
image
image

**Comment by maryrae-qa** [comment]
iPhone 6Plus -- Largest Fonts/Display
IMG_0031
iPhone 6Plus -- Dafault Fonts/Display
IMG_0032

Android - MotoG6 -- Largest Fonts/Display
Screenshot_20210330-164454
Android - MotoG6 -- Default Fonts/Display
Screenshot_20210330-164608

iPhone 6S-- Largest Fonts/Display
IMG_0022
iPhone 6S -- Default Fonts/Display
IMG_0021

Android - Lg4G  -- Largest Fonts/Display
Screenshot_2021-03-30-16-56-21
Android - Lg4G  -- Default Fonts/Display
Screenshot_2021-03-30-17-02-00

Android - Pixel2 -- Largest Fonts/Display
Screenshot_20210330-164858
Android - Pixel2 -- Default Fonts/Display
Screenshot_20210330-164954
Android - Pixel2 -- Default Fonts/Display - Alert OFF
Screenshot_20210330-165135

**Comment by aklef** [comment]
From yesterday's test build of this here's accessibility enabled with the smallest font/biggest font sizes imageimage

**Pull request merged**
