### PR TITLE
Fix/blank region value

### PR DESCRIPTION
**Pull request by craigzour**
# Summary | Résumé

- Fixed for Region set to "" instead of "None" in both native layers

### CODE REVIEW

**Comment by timarney** [comment]
What's the best way to test this?

**Comment by craigzour** [comment]
@timarney I did test it myself but I guess we could just this build on several devices where we do not select any region during the onboarding. Then we would have to check on the server side if we are getting metrics with a region set to "" (which should not be the case anymore)

**Comment by timarney** [comment]
Going to approve and we'll test in the next staging builds.

**Review by timarney — APPROVED** [review]

**Comment by patheard** [comment]
Happy to check for test payloads if you let me know what I should be looking for in DynamoDB.

**Pull request merged**
