### PR TITLE
Update text formatting - your visits

### PR DESCRIPTION
**Pull request by timarney**
## Notes

@katewilhelm @EliseKa 

This screen has been updated to use the  [updated text component](https://github.com/cds-snc/covid-alert-app/pull/1518) which supports bold text by using `**` wrapped around the text you would like to bold.

## Marking text as bold
Screen Shot 2021-04-30 at 7 40 02 AM

https://github.com/cds-snc/covid-alert-app/pull/1544/files#diff-99beebd24c58939a434c8c0581f97b321686e6574d5211ee1c2ca46fcb253deaR232

## Updated screens

Let me know if these updated screen look correct now.

**FR** 

**EN**

### CODE REVIEW

**Comment by EliseKa** [comment]
@timarney Very cool. It's only part of the sentence that should be bold, as follows:

EN: **Your visits are not shared** with anyone.
FR: Vos visites **ne sont communiquées à personne.**

cc @katewilhelm

**Comment by timarney** [comment]
Updated

Screen Shot 2021-04-30 at 9 27 36 AM

**Review by EliseKa — APPROVED** [review]
looks good thank you!

**Review by omartehsin1 — APPROVED** [review]

**Comment by timarney** [comment]
image
image-1

**Comment by timarney** [comment]
image

**Comment by katewilhelm** [comment]
Hey @timarney in the reference screen shot of English, the last sentence should be in its own paragraph.

**Pull request merged**
