### PR TITLE
[updated] use in-ecosystem URL for reachability, instead of leaking info to Google 

### PR DESCRIPTION
**Pull request by nickmly**
Copied from #1004. This PR fixes a CI issue that was occurring with #1004.

# Summary

The app leaks IP addresses to Google. This fixes it. Explanation in [issue](https://github.com/cds-snc/covid-alert-app/issues/1003).

# Test instructions

You'll need [this PR](https://github.com/cds-snc/covid-alert-server/pull/241) deployed before this can really be tested. Once ready, analyze traffic to be sure that no data is flowing to Google, and instead is staying local on `canada.ca`

# Reviewer checklist

This is a suggested checklist of questions reviewers might ask during their review:

- [ ] Does this meet a user need?
- [ ] Is it accessible?
- [ ] Is it translated between both offical languages?
- [ ] Is the code maintainable?
- [ ] Have you tested it?
- [ ] Are there automated tests?
- [ ] Does this cause automated test coverage to drop?
- [ ] Does this break existing functionality?
- [ ] Should this be split into smaller PRs to decrease change risk?
- [ ] Does this change the privacy policy?
- [ ] Does this introduce any security concerns?
- [ ] Does this significantly alter performance?
- [ ] What is the risk level of using added dependencies?
- [ ] Should any documentation be updated as a result of this? (i.e. README setup, etc.)

### CODE REVIEW

**Comment by dsamojlenko** [comment]
This is fine. I'll note that the reachability url does not have an effect on the app state. ie, replacing the 'presence' url with any dummy url would cause the reachability request not to fire at all, but our `network.isConnected` check would not fail.

**Comment by scoates** [comment]
FWIW, I think that not firing the request (at least not so often) is probably even better. My main concern was the third party, though.

**Comment by dsamojlenko** [comment]
Agreed. For reference, here's what network traffic at startup looks like with default config:
image

This is with our custom url enabled:
image

And here it is if we just provide an empty string for the reachabilityURL:
image

Code:
```
NetInfo.configure({
  reachabilityUrl: '',
});
```

Personally, I think fewer network calls is better.

**Comment by scoates** [comment]
I'm on board if there's no other downside. Captive portals should still fail because of the https here, so the risk of injection is moot (or at least pushed down to the device's trust authority). Reduces load on the server, too.

**Comment by scoates** [comment]
Thanks!

Is there somewhere I can read about how releases work after this? If not, is there a short version you can share?

**Pull request merged**
