### PR TITLE
Speed up drawer transition

### PR DESCRIPTION
**Pull request by timarney**
**Before:**
Screen Shot 2020-07-29 at 9 52 15 AM

**Current PR**

NOTE: this video is slowed down so not real time

https://www.youtube.com/watch?v=TnFUD8xhI4g&feature=youtu.be

### CODE REVIEW

**Comment by timarney** [comment]
Ref: https://github.com/cds-snc/covid-alert-app/issues/929

**Comment by nickmly** [comment]
Tested on iOS and Android, LGTM

**Comment by timarney** [comment]
@smcmurtry let me know if that bug you found has anything to do with this PR

**Comment by smcmurtry** [comment]
Okay I was able to track down the bug and it looks like it is related to this PR, specifically the `callbackThreshold`. I am showing touch events so hopefully you can see what is going on:

`callbackThreshold` not set: https://youtu.be/JbfWOwK-x_U

`callbackThreshold={0.9}`: https://youtu.be/5ogegS8G6Zs

**Comment by timarney** [comment]
Closing this as it's not the best way forward.

**Pull request closed without merging**
