### PR TITLE
Check location service on Android

### PR DESCRIPTION
**Pull request by henrytao-me**
Resolves https://github.com/cds-snc/covid-alert-app/issues/891

## How to test
- Run
```
rm -rf node_modules/react-native-system-setting
yarn add react-native-system-setting@1.7.4
yarn
```
- Open the app, pass onboarding flow and enable EN. 
- Verify CovidAlert is active.
- Go to device settings, disable location.
- Back to the app, verify CovidAlert is inactive. 
- Turn on EN in the app, verify that location is enabled. 
- Turn off bluetooth. 
- Back to the app, verify CovidAlert is inactive.
- Turn on EN in the app, verify that bluetooth is enabled. 
- Keep the app in foreground, toggle Location off in notification bar (not system settings), verify that the app change status properly.

### CODE REVIEW

**Comment by timarney** [comment]
Checking now

**Comment by henrytao-me** [comment]
Ready for reviewing

**Comment by smcmurtry** [comment]
I followed the testing steps on my Android device and it all looks good to me. Successfully logged out the system status as `location_off`. I couldn't test turning off location from the top menu though since I don't have it - maybe it was introduced after Android 7.1?

I am seeing the fall through "Something went wrong" screen now when location is off (as expected since we are not handling this state yet):
Screen Shot 2020-07-24 at 4 25 05 PM

We need to show the user something more like the `ExposureNotificationsDisabledView`, with a button to turn on the framework. I think we can move the android location specific content there but I will check w/ @katewilhelm. 

I think this is good to go but probably we should wait to merge until we have that new screen set up. What do you think @timarney?

**Comment by timarney** [comment]
Yes we'll hold until next week.

**Comment by henrytao-me** [comment]
@timarney Did you do `yarn` to install the react-native-system-setting patch again?

**Comment by timarney** [comment]
Will check priority is https://github.com/cds-snc/covid-alert-app/pull/909 this A.M

**Comment by timarney** [comment]
@henrytao-me 

yes 

```
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ patch-package
patch-package 6.2.2
Applying patches...
react-native-background-fetch@3.1.0 ✔
react-native-system-setting@1.7.4 ✔
✨  Done in 1.55s.
```

**Comment by henrytao-me** [comment]
I just rebased master and gate location permission for Android only. The quick control for location works for me too. 🤔

**Comment by smcmurtry** [comment]
@timarney @henrytao-me I've added the new screen: https://youtu.be/_g_Q-m8pXtY

**Comment by timarney** [comment]
This is on hold for now.

**Comment by emilykuret** [comment]
[More specific screen for "Your location is off"](https://trello.com/c/KUHEuO4N/269-more-specific-screen-for-your-location-is-off)

**Comment by timarney** [comment]
@jeberhardt please give this a test.  Last time I tested it was working but ended up in out build back log.

Looking to confirm this is good to go when we're ready to include it.

**Comment by timarney** [comment]
Retested this

This should be rolled in with a release including

https://github.com/cds-snc/covid-alert-app/pull/934

**Comment by timarney** [comment]
@smcmurtry you might want to re-test this as well to confirm it landing on the right page.

Mostly around this part.

https://github.com/cds-snc/covid-alert-app/pull/892/files#diff-bb2a692e69dc457e8a5d5757bdaf9a3bR86

**Comment by timarney** [comment]
Will use the replacement branch https://github.com/cds-snc/covid-alert-app/pull/1045

**Pull request closed without merging**
